version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  alu:
    lang: python3
    handler: ./alu
    image: zhenmei/alu:latest
    requirements: ./alu/alu_requirements.txt
  keyDownloader:
    lang: python3
    handler: ./keydownloader
    image: zhenmei/keydownloader:latest
    requirements: ./keydownloader/keydownloader_requirements.txt
  together:
    lang: python3
    handler: ./together
    image: zhenmei/together:latest
    requirements: ./together/together_requirements.txt

